@startwbs sas
*[#SkyBlue] Создание колаборативного инструмента\nдля проектирования компьютерных игр
**[#pink] 1. Анализ 
***_  1.1 Описание предметной\nобласти
***_  1.2 Анализ существующих\nрешений
***_  1.3 Формирование\nтребований
***_  1.4 Разработка технического\nзадания
**[#pink] 2. Проектирование
***_  2.1 Формализация требований\nс помощью диаграмм прецедентов
***_  2.2 Разработка архитектуры\nприложения
***_  2.3 Моделирование поведения\nсистемы с помощью\nдиаграмм последовательностей
***_  2.4 Проектирование\nбазы данных
***_  2.5 Создание концепта\nпользовательского интерфейса
***_  2.6 Проектирование алгоритмов
***_  2.7 Добавить диаграммы классов
**[#pink] 3. Разработка
***_  3.1 Реализовать серверную\nчасть приложения
***_  3.2 Реализовать базу\nданных
***_  3.3 Реализовать клиентскую\nчасть приложения
***_  3.4 Разработка\nпользовательской\nдокументации
**[#pink] 4. Тестирование
***_  4.1 Создание UNIT тестов
***_  4.2 Ручное тестирование\n(черный ящик)
***_  4.3 Создание отчёта\nо тестировании
**[#pink] 5. Внедрение
***_  5.1 Развернуть серверную часть\nприложения на стороннем хостинге
***_  5.2 Протестировать работу\nприложения со сторонних компьютеров
@endwbs