@startuml board
autonumber
actor "Пользователь" as u
participant "Браузер" as f
participant "boardComponent" as bc
participant "boardStore" as bs 
participant "websocketController" as wc 
participant "elementService" as es
actor "Остальные пользователи\nна доске" as o

group 2. Пользователь изменяет элементы на доске
u -> f : Вносит изменение\nна доске
activate f
f -> bs : Посылает изменения пользователя
activate bs
bs -> bs : Вносит изменения\nлокально
bs ->> bc : Компонент извещается\nоб изменениях
deactivate bs
activate bc
bc -->> f : Изменяет страницу
bc ->> es : Посылает изменения
activate es
es -> es : Сохраняет изменения
deactivate es
bc ->> wc : Посылает сигнал с изменениями
deactivate bc
activate wc
wc ->> o : Извещает подписанных\nна данную доску пользователей\nоб изменениях
deactivate wc
activate o
o -> o : Вносит изменения\nу себя
deactivate o
f -->> u : Показывает обновленную\nстраницу
deactivate f
end

@enduml