@startuml board
autonumber
actor "Пользователь" as u
participant "Frontend" as f
participant "Editor Service" as e
database "База данных" as db
actor "Остальные пользователи\nна доске" as o

group 1. Создать элемент на доске
u -> f : Выбирает элемент,\nкоторый хочет создать
f -> e : Посылает элемент, который\nпользователь хочет создать
e -> e : Создаёт элемент
e -> e : Сохраняет в историю\nизменений
e -> db : Сохраняет элемент
db -->> e : Сохранил
Par 
e ->> o : Обновляет информацию\nу остальных пользователей
else
e -->> f : Обновляет информацию\nу пользователя
f -->> u : Показывает созданный элемент
end
end

@enduml