@startuml board
autonumber
actor "Пользователь" as u
participant "Frontend" as f
participant "Editor Service" as e
database "База данных" as db
actor "Остальные пользователи\nна доске" as o

group 5. Группировать элементы на доске
u -> f : Выбирает элементы,\nкоторые хочет объединить в группу
f -->> u : Отмечает выбранные элементы
u -> f : Выполняет команду\n"Объединить в группу"
f -> e : Посылает элементы, которые\n пользователь объединил
e -> e : Создаёт новую группу
e -> e : Сохраняет в историю\nизменений
e -> db : Сохраняет изменения
db -->> e : Сохранил
Par 
e ->> o : Обновляет информацию\nу остальных пользователей
else
e -->> f : Обновляет информацию\nу пользователя
f -->> u : Показывает обновленные элементы
end
end

@enduml