@startuml board
autonumber
actor "Пользователь" as u
participant "Frontend" as f
participant "Editor Service" as e
database "База данных" as db
actor "Остальные пользователи\nна доске" as o

group 2. Обновить/удалить элемент на доске
u -> f : Выбирает элемент,\nкоторый хочет обновить
f -->> u : Переводит пользователя\nв режим редактирования
u -> f : Вносит изменения\nв элемент
f -> e : Посылает элемент, который\n пользователь обновил
e -> e : Обновляет элемент
e -> e : Сохраняет в историю\nизменений
e -> db : Сохраняет изменения
db -->> e : Сохранил
Par 
e ->> o : Обновляет информацию\nу остальных пользователей
else
e -->> f : Обновляет информацию\nу пользователя
f -->> u : Показывает обновленный элемент
end
end

@enduml