@startuml comment
autonumber
actor "Комментатор" as c
participant "Frontend" as f
participant "Editor Service" as s
database "База данных" as db

group 10. Оставить комментарий на доске
c -> f : Выбирает элемент\nк которому оставит комментарий
f -->> c : Выделяет элемент
c -> f : Вводит комментарий
f -> s : Отправляет комментарий
s -> db : Сохраняет комментарий
db -->> s : Подтверждает сохранение
s -->> f : Подтверждает успешное сохранение
f -->> c : Отображает комментарий
end
@enduml