@startuml create_invitation
autonumber
actor "Пользователь" as d
participant "Frontend" as f
participant "Invitation Service" as i
database "База данных" as db

group 8. Пригласить пользователя в проект
d -> f : Нажимает "Пригласить пользователя"
f -->> d : Выводит варианты ролей\n(Редактор, комментатор, читатель)
d -> f : Выбирает нужную роль
f -->> d : Выводит поиск пользователя
d -> f : Находит нужного пользователя
f -> i : Запрашивает создание приглашения
i -> i : Создаёт приглашение пользователю
i -> db : Сохраняет приглашение
db -->> i : Подтверждает сохранение
i -->> f : Подтверждает создание\nприглашения
f -->> d : Отображает сообщение о том, что\nприглашение создано


end
@enduml