@startuml readonly
autonumber
actor "Пользователь" as u
participant "Frontend" as f
participant "Invitation Service" as i
participant "Project Service" as ps
database "База данных" as pdb
participant "Board Service" as bs
participant "User Service" as us

group 11. Просматривать проект/доски по ссылке
u -> f : Переходит по ссылке
f -> i : Запрашивает данные
i -> i : Проверяет, что ссылка действительна
alt Ссылка на проект
    i -> ps : Запрашивает данные
    ps -> pdb : Получает данные проекта
    pdb -->> ps : Возвращает данные
    ps -->> i : Возвращает проект
    i -->> f : Передает данные проекта
    f -> us : Запрашивает случайное имя
    us -> us : Генерирует случайное имя
    us -->> f : Возвращает случайное имя
    f -->> u : Отображает проект\nиспользует сгенерированное имя\nдля отображения пользователя
else Ссылка на доску
    i -> bs : Запрашивает данные доски
    bs -> pdb : Получает данные доски
    pdb -->> bs : Возвращает данные
    bs -->> i : Возвращает данные доски
    i -->> f : Передает данные доски
    f -> us : Запрашивает случайное имя
    us -> us : Генерирует случайное имя
    us -->> f : Возвращает случайное имя
    f -->> u : Отображает доску\nиспользует сгенерированное имя\nдля отображения пользователя
end
end
@enduml