@startuml undo
autonumber
actor "Пользователь" as u
participant "Frontend" as f
participant "Editor Service" as e
database "База данных" as db
actor "Остальные пользователи\nна доске" as o

group 4. Отменить изменение на доске
u -> f : Нажимает сочетание клавиш\nИЛИ\nВыбирает соответствующий пункт в меню
f -> e : Посылает команду\nотменить изменение\nсделанного пользователем
e -> e : Проверяет историю\nизменений
alt В истории изменений есть действия
e -> e : Отменяет последнее изменение
e -> db : Сохраняет изменения
db -->> e : Сохранил
Par 
e ->> o : Обновляет информацию\nу остальных пользователей
else
e -->> f : Обновляет информацию\nу пользователя
end
f -->> u : Показывает обновленное\nсостояние доски
else Нет действий
e -->> f : Ничего не происходит
f -->> u : Ничего не изменяется
end
end

@enduml