version: '3.3'
services:
    frontend:
        image: mentalsmoge/frontend:latest
        container_name: monolith_frontend
        environment:
            NODE_ENV: development
            WATCHPACK_POLLING: "true"
        build: frontend/
        volumes:
            - ./frontend:/app_frontend
            # - ./frontend/node_modules:/app_frontend/node_modules
            - /app_frontend/node_modules
        ports:
            - "3000:5173"
        depends_on:
            - backend
        networks:
            - app-network
        command: sh -c "npm install && npm run dev"
    backend:
        image: mentalsmoge/backend:latest
        container_name: monolith_backend
        build: backend/
        depends_on:
            - user_db
        ports:
            - "8080:8080"
            - "8082:8082"
        environment:
            - RETHINKDB_HOST=${RETHINKDB_HOST}
            - RETHINKDB_PORT=${RETHINKDB_PORT}
            - RETHINKDB_NAME=${RETHINKDB_NAME}
            - DB_HOST=user_db
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_PORT=5432
        volumes:
            - ./backend:/app_backend
        networks:
            - app-network

    # redis:
    #     container_name: monolith_redis
    #     image: redis:alpine
    #     ports:
    #         - "6379:6379"
    #     volumes:
    #         - redis_data:/data
    #     networks:
    #         - app-network
    # rethink_db:
    #     container_name: monolith_editor_db
    #     image: rethinkdb:latest
    #     ports:
    #         - "28015:28015"
    #         - "8081:8080"
    #     volumes:
    #         - rethinkdb-data:/data
    #     networks:
    #         - app-network
    user_db:
        container_name: monolith_user_db
        image: postgres:17-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - .backend/db/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - app-network
        ports:
            - "5432:5432"
    # pgadmin:
    #     container_name: monolith_pgadmin_container
    #     image: dpage/pgadmin4:9
    #     environment:
    #         PGADMIN_DEFAULT_EMAIL: "mentalsmoge@gmail.com"
    #         PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
    #         PGADMIN_CONFIG_SERVER_MODE: "False"
    #     depends_on:
    #         - user_db
    #     volumes:
    #         - pgadmin-data:/var/lib/pgadmin
    #     ports:
    #         - "5050:80"
    #     restart: unless-stopped
    #     deploy:
    #         resources:
    #             limits:
    #                 cpus: "0.5"
    #                 memory: 1G
    #     networks:
    #         - app-network

volumes:
    postgres-data:
        # pgadmin-data:
        # rethinkdb-data:
        # redis_data:
networks:
    app-network:
        driver: bridge
