version: '3.3'
name: "monolith"
services:
    frontend:
        image: mentalsmoge/frontend:latest
        container_name: monolith_frontend
        environment:
            NODE_ENV: development
            WATCHPACK_POLLING: "true"
        build: frontend/
        volumes:
            - ./frontend:/app_frontend
            - /app_frontend/node_modules
        ports:
            - "3000:5173" # Доступно извне
        depends_on:
            - backend
        networks:
            - external-network # Только внешняя сеть
        command: sh -c "npm install && npm run dev"
    redis:
        container_name: monolith_redis
        image: redis:alpine
        ports:
            - "6379:6379"
        volumes:
            - redis_data:/data
        networks:
            - internal-network
    backend:
        image: mentalsmoge/backend:latest
        container_name: monolith_backend
        build: backend/
        depends_on:
            - user_db
        ports:
            - "8080:8080" # Для фронтенда
            - "8082:8082" # Для фронтенда
        environment:
            - RETHINKDB_HOST=${RETHINKDB_HOST}
            - RETHINKDB_PORT=${RETHINKDB_PORT}
            - RETHINKDB_NAME=${RETHINKDB_NAME}
            - DB_HOST=user_db
            - DB_USER=${DB_USER}
            - DB_PASSWORD=${DB_PASSWORD}
            - DB_NAME=${DB_NAME}
            - DB_PORT=5432
        volumes:
            - images_volume:/app_backend/public/images
        networks:
            - internal-network # Внутренняя сеть для БД
            - external-network # Внешняя сеть для фронтенда

    user_db:
        container_name: monolith_user_db
        image: postgres:17-alpine
        volumes:
            - postgres-data:/var/lib/postgresql/data
            - .backend/init.sql:/docker-entrypoint-initdb.d/init.sql
        environment:
            - POSTGRES_USER=${DB_USER}
            - POSTGRES_PASSWORD=${DB_PASSWORD}
            - POSTGRES_DB=${DB_NAME}
        networks:
            - internal-network # Только внутренняя сеть
        expose:
            - "5432" # Только для внутреннего использования
    pgadmin:
        container_name: monolith_pgadmin_container
        image: dpage/pgadmin4:9
        environment:
            PGADMIN_DEFAULT_EMAIL: "mentalsmoge@gmail.com"
            PGADMIN_DEFAULT_PASSWORD: ${DB_PASSWORD}
            PGADMIN_CONFIG_SERVER_MODE: "False"
        depends_on:
            - user_db
        volumes:
            - pgadmin-data:/var/lib/pgadmin
        ports:
            - "5050:80"
        restart: unless-stopped
        deploy:
            resources:
                limits:
                    cpus: "0.5"
                    memory: 1G
        networks:
            - internal-network # Внутренняя сеть для БД
            - external-network # Внешняя сеть для фронтенда

volumes:
    postgres-data:
    images_volume:
    pgadmin-data:
    redis_data:


networks:
    internal-network:
        driver: bridge
        internal: true # Полностью изолированная сеть

    external-network:
        driver: bridge
        internal: false # Доступна извне
